# This file generates firmware for your Lily58 Pro with RGB and encoder
# Place this as: build.yaml in your zmk-config repository

include:
  - board: nice_nano_v2
    shield: lily58_left
  - board: nice_nano_v2
    shield: lily58_right
